// Interface automatically generated by schemas-to-ts

import { ProductTag } from '../../../product-tag/content-types/product-tag/product-tag';
import { ProductTag_Plain } from '../../../product-tag/content-types/product-tag/product-tag';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface ProductsPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    filterTitle1: string;
    filterTitle2: string;
    filterTitle3: string;
    filter_list_1: { data: ProductTag[] };
    filter_list_2: { data: ProductTag[] };
    filter_list_3: { data: ProductTag[] };
  };
}
export interface ProductsPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  filterTitle1: string;
  filterTitle2: string;
  filterTitle3: string;
  filter_list_1: ProductTag_Plain[];
  filter_list_2: ProductTag_Plain[];
  filter_list_3: ProductTag_Plain[];
}

export interface ProductsPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  filterTitle1: string;
  filterTitle2: string;
  filterTitle3: string;
  filter_list_1: number[];
  filter_list_2: number[];
  filter_list_3: number[];
}

export interface ProductsPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  filterTitle1: string;
  filterTitle2: string;
  filterTitle3: string;
  filter_list_1: AdminPanelRelationPropertyModification<ProductTag_Plain>;
  filter_list_2: AdminPanelRelationPropertyModification<ProductTag_Plain>;
  filter_list_3: AdminPanelRelationPropertyModification<ProductTag_Plain>;
}
