[build]
base = "."

[[buildPhases]]
name = "Install dependencies"
run = "cd /frontend && npm install"

[[buildPhases]]
name = "Build"
run = "cd /frontend && npm run build"

[start]
base = "."
command = "cd /frontend && npm start"

[language]
name = "node"