providers = ['node']

[phases.setup]
nixPkgs = ['node', 'npm']

[phases.install]
cmds = ['cd /frontend && npm install']

[phases.build]
cmds = ['cd /frontend && npm run build']

[phases.start]
cmd = 'cd /frontend && npm run start'