[phases.setup]
nixPkgs = ['node', 'npm']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[phases.start]
cmd = 'npm run start'
[phases.start]
workdir = "/frontend"

[overlays]
# Include the parent directory as an overlay
. = ./
