// Interface automatically generated by schemas-to-ts

export interface Link {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    text: string;
    href: string;
  };
}
export interface Link_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text: string;
  href: string;
}

export interface Link_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text: string;
  href: string;
}

export interface Link_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text: string;
  href: string;
}
