// Interface automatically generated by schemas-to-ts

import { Product } from '../../../product/content-types/product/product';
import { User } from '../../../../common/schemas-to-ts/User';
import { Product_Plain } from '../../../product/content-types/product/product';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Status {
  Completed = 'Completed',
  Shipped = 'Shipped',
  Delivered = 'Delivered',
  Refunded = 'Refunded',}

export interface Order {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    total?: number;
    products: { data: Product[] };
    status?: Status;
    user?: { data: User };
  };
}
export interface Order_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  total?: number;
  products: Product_Plain[];
  status?: Status;
  user?: User_Plain;
}

export interface Order_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  total?: number;
  products: number[];
  status?: Status;
  user?: number;
}

export interface Order_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  total?: number;
  products: AdminPanelRelationPropertyModification<Product_Plain>;
  status?: Status;
  user?: AdminPanelRelationPropertyModification<User_Plain>;
}
