// Interface automatically generated by schemas-to-ts

import { User } from '../../../../common/schemas-to-ts/User';
import { OrderProduct } from '../../../../components/product/interfaces/OrderProduct';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { OrderProduct_Plain } from '../../../../components/product/interfaces/OrderProduct';
import { OrderProduct_NoRelations } from '../../../../components/product/interfaces/OrderProduct';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Status {
  Completed = 'Completed',
  Shipped = 'Shipped',
  Delivered = 'Delivered',
  Refunded = 'Refunded',}

export interface Order {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    total?: number;
    status?: Status;
    user?: { data: User };
    referenceId: string;
    purchasedVariants: OrderProduct[];
    city: string;
    country: string;
    line1: string;
    line2?: string;
    postalCode: string;
    state: string;
    name: string;
  };
}
export interface Order_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  total?: number;
  status?: Status;
  user?: User_Plain;
  referenceId: string;
  purchasedVariants: OrderProduct_Plain[];
  city: string;
  country: string;
  line1: string;
  line2?: string;
  postalCode: string;
  state: string;
  name: string;
}

export interface Order_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  total?: number;
  status?: Status;
  user?: number;
  referenceId: string;
  purchasedVariants: OrderProduct_NoRelations[];
  city: string;
  country: string;
  line1: string;
  line2?: string;
  postalCode: string;
  state: string;
  name: string;
}

export interface Order_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  total?: number;
  status?: Status;
  user?: AdminPanelRelationPropertyModification<User_Plain>;
  referenceId: string;
  purchasedVariants: OrderProduct_Plain[];
  city: string;
  country: string;
  line1: string;
  line2?: string;
  postalCode: string;
  state: string;
  name: string;
}
