// Interface automatically generated by schemas-to-ts

import { Link } from '../../../link/content-types/link/link';
import { Link_Plain } from '../../../link/content-types/link/link';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Footer {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    slogan: string;
    column1Title: string;
    column2Title: string;
    column3Title: string;
    column_1_links: { data: Link[] };
    column_2_links: { data: Link[] };
    column_3_links: { data: Link[] };
  };
}
export interface Footer_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slogan: string;
  column1Title: string;
  column2Title: string;
  column3Title: string;
  column_1_links: Link_Plain[];
  column_2_links: Link_Plain[];
  column_3_links: Link_Plain[];
}

export interface Footer_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slogan: string;
  column1Title: string;
  column2Title: string;
  column3Title: string;
  column_1_links: number[];
  column_2_links: number[];
  column_3_links: number[];
}

export interface Footer_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slogan: string;
  column1Title: string;
  column2Title: string;
  column3Title: string;
  column_1_links: AdminPanelRelationPropertyModification<Link_Plain>;
  column_2_links: AdminPanelRelationPropertyModification<Link_Plain>;
  column_3_links: AdminPanelRelationPropertyModification<Link_Plain>;
}
