// Interface automatically generated by schemas-to-ts

import { Link } from '../../../link/content-types/link/link';
import { Link_Plain } from '../../../link/content-types/link/link';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Navbar {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    links: { data: Link[] };
  };
}
export interface Navbar_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  links: Link_Plain[];
}

export interface Navbar_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  links: number[];
}

export interface Navbar_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  links: AdminPanelRelationPropertyModification<Link_Plain>;
}
