// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Category } from '../../../category/content-types/category/category';
import { ProductTag } from '../../../product-tag/content-types/product-tag/product-tag';
import { ProductSize } from '../../../product-size/content-types/product-size/product-size';
import { ProductColor } from '../../../product-color/content-types/product-color/product-color';
import { Category_Plain } from '../../../category/content-types/category/category';
import { ProductTag_Plain } from '../../../product-tag/content-types/product-tag/product-tag';
import { ProductSize_Plain } from '../../../product-size/content-types/product-size/product-size';
import { ProductColor_Plain } from '../../../product-color/content-types/product-color/product-color';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    slug: string;
    isBestSeller: boolean;
    description: string;
    price: number;
    discountPercent: number;
    images?: { data: Media[] };
    category?: { data: Category };
    product_tags?: { data: ProductTag[] };
    product_sizes?: { data: ProductSize[] };
    product_colors?: { data: ProductColor[] };
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  isBestSeller: boolean;
  description: string;
  price: number;
  discountPercent: number;
  images?: Media[];
  category?: Category_Plain;
  product_tags?: ProductTag_Plain[];
  product_sizes?: ProductSize_Plain[];
  product_colors?: ProductColor_Plain[];
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  isBestSeller: boolean;
  description: string;
  price: number;
  discountPercent: number;
  images?: number[];
  category?: number;
  product_tags?: number[];
  product_sizes?: number[];
  product_colors?: number[];
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  isBestSeller: boolean;
  description: string;
  price: number;
  discountPercent: number;
  images?: AdminPanelRelationPropertyModification<Media>[];
  category?: AdminPanelRelationPropertyModification<Category_Plain>;
  product_tags?: AdminPanelRelationPropertyModification<ProductTag_Plain>;
  product_sizes?: AdminPanelRelationPropertyModification<ProductSize_Plain>;
  product_colors?: AdminPanelRelationPropertyModification<ProductColor_Plain>;
}
