// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { ProductColor } from '../../../product-color/content-types/product-color/product-color';
import { ProductSize } from '../../../product-size/content-types/product-size/product-size';
import { ProductColor_Plain } from '../../../product-color/content-types/product-color/product-color';
import { ProductSize_Plain } from '../../../product-size/content-types/product-size/product-size';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    slug: string;
    isBestSeller: boolean;
    description?: string;
    price: number;
    discountPercent: number;
    images?: { data: Media[] };
    product_colors: { data: ProductColor[] };
    product_sizes: { data: ProductSize[] };
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  isBestSeller: boolean;
  description?: string;
  price: number;
  discountPercent: number;
  images?: Media[];
  product_colors: ProductColor_Plain[];
  product_sizes: ProductSize_Plain[];
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  isBestSeller: boolean;
  description?: string;
  price: number;
  discountPercent: number;
  images?: number[];
  product_colors: number[];
  product_sizes: number[];
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  isBestSeller: boolean;
  description?: string;
  price: number;
  discountPercent: number;
  images?: AdminPanelRelationPropertyModification<Media>[];
  product_colors: AdminPanelRelationPropertyModification<ProductColor_Plain>;
  product_sizes: AdminPanelRelationPropertyModification<ProductSize_Plain>;
}
