// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Link } from '../../../link/content-types/link/link';
import { Link_Plain } from '../../../link/content-types/link/link';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface AboutPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    heroTitle: string;
    heroSubtitle: string;
    heroImage: { data: Media };
    leftImage1: { data: Media };
    leftImage2: { data: Media };
    title: string;
    link?: { data: Link };
    description: string;
  };
}
export interface AboutPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  heroTitle: string;
  heroSubtitle: string;
  heroImage: Media;
  leftImage1: Media;
  leftImage2: Media;
  title: string;
  link?: Link_Plain;
  description: string;
}

export interface AboutPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  heroTitle: string;
  heroSubtitle: string;
  heroImage: number;
  leftImage1: number;
  leftImage2: number;
  title: string;
  link?: number;
  description: string;
}

export interface AboutPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  heroTitle: string;
  heroSubtitle: string;
  heroImage: AdminPanelRelationPropertyModification<Media>;
  leftImage1: AdminPanelRelationPropertyModification<Media>;
  leftImage2: AdminPanelRelationPropertyModification<Media>;
  title: string;
  link?: AdminPanelRelationPropertyModification<Link_Plain>;
  description: string;
}
